on:
  push:
    branches:
      - main

name: Run Release
jobs:
  go-release:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@latest
        with:
          ref: ${{ needs.release-please.outputs.release_tag_name }}

      - name: Set up Go
        uses: actions/setup-go@latest
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@latest
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}