on:
  push:
    tags:
      - '*'

env:
  PROJECT: test
  TAG : 0.6

name: Run Release
jobs:
  go-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Download syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/open-feature/flagd:v0.3.4
          artifact-name: ${{ format('{0}-{1}-sbom.spdx',env.REGISTRY, env.TAG) }}