on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PROJECT: test
  TAG: 0.12
  PUBLIC_KEY_FILE: publicKey.pub

name: Run Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          ref: main

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        id: build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: false
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}

  go-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: CheckDigest
        run: echo "${{ needs.build.outputs.image_digest }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Download syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image SBOM file name
        id: image-sbom-id
        run: echo "IMAG_SBOM_FILE=${{ format('flagd-{0}-sbom.spdx', env.TAG) }}" >> $GITHUB_OUTPUT

      - name: SBOM for latest image
        uses: anchore/sbom-action@07978da4bdb4faa726e52dfc6b1bed63d4b56479 # v0
        with:
          image: ghcr.io/open-feature/flagd:v0.3.7
          artifact-name: ${{ steps.image-sbom-id.outputs.IMAG_SBOM_FILE }}

      - name: Bundle release assets
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            ${{ steps.image-sbom-id.outputs.IMAG_SBOM_FILE }}